### ISSUE TITLE
gambit js backend

### ISSUE THREAD

**Issue by amirouche** [scheme-containers/gambit#1]
When trying to compile a simple scheme file to javascript I get an error:

```sh
% cat out.scm
(display 42)
% gsc -target js -exe out.scm
*** ERROR -- missing or invalid linking information for module "/usr/local/lib/_gambit"
cat: /usr/local/lib/_gambit.js: No such file or directory
%
```

I started the container with the following command:

```
docker run -v $(pwd):/mnt --rm -it schemers/gambit bash
```

**Comment by lassik** [comment]
`schemers/gambit` is the latest release (4.9.3). Try `schemers/gambit:head`.

**Comment by amirouche** [comment]
Same issue:

```
$ docker run -v $(pwd):/mnt --rm -it schemers/gambit:head bash
root@beb248ad2998:/tmp# cd /mnt/
root@beb248ad2998:/mnt# gsc -target js -exe main.scm
*** ERROR -- missing or invalid linking information for module "/usr/local/lib/_gambit"
cat: /usr/local/lib/_gambit.js: No such file or directory
root@beb248ad2998:/mnt#
```

**Comment by amirouche** [comment]
Apparantly we need to do `make _gambit.js` to create that file.

ref: https://github.com/gambit/gambit/issues/404#issuecomment-522070832

**Comment by lassik** [comment]
Can be. I haven't had the chance to try out Gambit's JS support yet.

Apparently our `:head` container is quite old; many commits have been made to Gambit since. I just started a rebuild from the latest master (we don't have automatic build triggers yet). Should be done in about an hour.

**Comment by amirouche** [comment]
@lassik can you run a build, if it is not already done? Thanks!

**Comment by lassik** [comment]
It should have been built automatically; all commits to these Dockerfile repos (master branch) do trigger a rebuild of the containers.

Let me know if you have a Docker Hub account and want to be added to the schemers organization there.
