### ISSUE TITLE
Retrigger a build of gambit head

### ISSUE THREAD

**Issue by amirouche** [scheme-containers/gambit#4]
@lassik can you retrigger a build of the container or tell me how to do it?

**Comment by lassik** [comment]
Sure, now rebuilding!

Every commit pushed to this repo will retrigger the build (including empty commits). Builds can also be manually triggered from the Docker Hub web UI; let me know if you have a Docker Hub account and want to be added to the org.

**Comment by lassik** [comment]
The `head` container last took about 40 minutes to build.

**Comment by amirouche** [comment]
Thanks!
